//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedicalRecord
    {
        public int ID_Record { get; set; }
        public int ID_Patient { get; set; }
        public Nullable<int> ID_Diagnosis { get; set; }
        public Nullable<int> ID_Procedure { get; set; }
        public Nullable<int> ID_Medication { get; set; }
        public Nullable<int> ID_Staff { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.DateTime VisitDate { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public int ID_Department { get; set; }
        public string Notes { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual MedicalProcedure MedicalProcedure { get; set; }
        public virtual Medication Medication { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
